version: "3.8"

services:
  sellerservice:
    build: ./seller-backend
    ports:
      - "4000:4000"
    environment:
      - DATABASE_SELLER_URL=${DATABASE_SELLER_URL}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRES_IN=${JWT_EXPIRES_IN}
    networks:
      - app-network

  buyerservice:
    build: ./buyer-backend
    ports:
      - "8989:8989"
    environment:
      - DATABASE_BUYER_URL=${DATABASE_BUYER_URL}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRES_IN=${JWT_EXPIRES_IN}
    networks:
      - app-network

  seller-frontend:
    build: ./seller-frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_BASE_URL_Seller=${REACT_APP_BASE_URL_Seller}
      - REACT_APP_BASE_Seller=${REACT_APP_BASE_Seller}
    networks:
      - app-network

  buyer-frontend:
    build: ./buyer-frontend
    ports:
      - "3001:3000"
    environment:
      - REACT_APP_BASE_URL_Buyer=${REACT_APP_BASE_URL_Buyer}
      - REACT_APP_BASE_Buyer=${REACT_APP_BASE_Buyer}
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
