version: "3.8"  # Updated to a valid version

services:
  sellerservice:
    build: ./seller-backend
    ports:
      - "4000:4000"  # Correct port mapping
    networks:
      - app-network  # Optional, but it's good practice to define networks

  buyerservice:
    build: ./buyer-backend
    ports:
      - "8989:8989"  # Correct port mapping
    networks:
      - app-network  # Optional, but it's good practice to define networks

  seller-frontend:
    build: ./seller-frontend  # Assuming you have a seller-frontend folder
    ports:
      - "3000:3000"  # Correct port mapping for frontend
    networks:
      - app-network  # Optional, but it's good practice to define networks

  buyer-frontend:
    build: ./buyer-frontend  # Assuming you have a buyer-frontend folder
    ports:
      - "3001:3000"  # Correct port mapping for frontend
    networks:
      - app-network  # Optional, but it's good practice to define networks

networks:
  app-network:  # Define a custom network if necessary
    driver: bridge
